// vue/boilerplate-combo/src/views/Callback.vue
<!-- src/views/Callback.vue -->
<template>
  <p>Signing in...</p>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import { useRouter } from 'vue-router'
import auth from '../service/auth'

const router = useRouter()

onMounted(async () => {
  await auth.completeLogin()
  await router.push('/')
})
</script>

// angular/boilerplate-combo/src/callback/callback.component.ts
// src/app/callback.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../services/auth.service';

@Component({
  standalone: true,
  selector: 'app-callback',
  template: `<p>Signing in...</p>`,
})
export class CallbackComponent implements OnInit {
  constructor(private auth: AuthService, private router: Router) {}

  async ngOnInit() {
    await this.auth.completeLogin();
    await this.router.navigateByUrl('/');
  }
}
